<?php

namespace AppBundle\Repository;

/**
 * CommandDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
